version: "2.3"

networks:
  default:
    name: md-reader
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:

  git-updater:
    image: greetgo/git-updater:0.0.1
    container_name: git-updater
    restart: always
    mem_limit: 700M
    volumes:
      - ~/volumes/md-reader-repo:/repo
      - ./updater:/updater
    command: ["sh", "/updater/run.sh"]

  md-reader: #                                         http://localhost:11000
    image: greetgo/md-reader:0.0.10
    container_name: md-reader
    restart: always
    mem_limit: 700M
    environment:
      MD_READER_URI_TOP: "index.md"
      MD_READER_WORK_DIR: "/data/mybpm-doc"
      MD_READER_HEADER_CAPTION: "MyBPM"
    ports:
      - "11000:8080"
      - "11001:5005"
    volumes:
      - ~/volumes/md-reader-repo:/data
